version: '3.5'

services:

  jupyterlab-dataops:
    container_name: jupyterlab-dataops
    image: gcr.io/getindata-images-public/jupyterlab-dataops:latest
    volumes:
    - ./:/home/jovyan/projects/lakehouse-analytics/:rw
    ports:
    - "8888:8888"
    stdin_open: true
    tty: true
    hostname: localhost
