jaffle_shop:
  target: snowflake
  outputs:

    snowflake:
      account: '{{ env_var(''SNOWFLAKE_ACCOUNT'') }}'
      database: DBT_ANALYTICS
      password: '{{ env_var(''SNOWFLAKE_PASSWORD'') }}'
      role: DBT_ROLE
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: DBT_USER
      warehouse: DBT_WH

    bigquery:
      type: bigquery
      dataset: '{{ env_var(''BIGQUERY_DATASET'') }}'
      project: '{{ env_var(''GCP_PROJECT_ID'') }}'
      location: '{{ env_var(''GCP_REGION'') }}'
      priority: '{{ env_var(''BIGQUERY_PRIORITY'') }}'
      threads: '{{ env_var(''BIGQUERY_THREADS'') | int }}'
      job_execution_timeout_seconds: '{{ env_var(''BIGQUERY_TIMEOUT'') | int }}'
      job_retries: '{{ env_var(''BIGQUERY_JOB_RETRIES'') | int }}'
      method: '{{ env_var(''GCP_AUTH_METHOD'') }}'
