
USE ROLE ACCOUNTADMIN;

CREATE DATABASE SNOWFLAKE_SAMPLE_DATA
FROM SHARE SFC_SAMPLES.SAMPLE_DATA;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE PUBLIC;

select * from snowflake_sample_data.tpch_sf1.customer limit 10;
