
USE DATABASE "SNOWFLAKE_SAMPLE_DATA";

ALTER SESSION SET USE_CACHED_RESULT = TRUE;

SELECT "NATION"."N_NAME" AS "N_NAME"
FROM "TPCH_SF1000"."ORDERS" "ORDERS"
  LEFT JOIN "TPCH_SF1000"."CUSTOMER" "CUSTOMER" ON ("ORDERS"."O_CUSTKEY" = "CUSTOMER"."C_CUSTKEY")
  LEFT JOIN "TPCH_SF1000"."NATION" "NATION" ON ("CUSTOMER"."C_NATIONKEY" = "NATION"."N_NATIONKEY")
GROUP BY 1;