# PyIceberg Catalog Configuration
# Place this file in your home directory as ~/catalog_config.yaml

# Databricks Unity Catalog
databricks:
  type: rest
  uri: https://<workspace-id>.cloud.databricks.com/api/2.1/unity-catalog/iceberg
  token: <your-databricks-personal-access-token>
  warehouse: <unity-catalog-name>

# Snowflake Polaris / REST Catalog
snowflake:
  type: rest
  uri: https://<account>.snowflakecomputing.com/polaris/api/catalog
  credential: <principal>:<secret>
  warehouse: <polaris-catalog-name>
  scope: PRINCIPAL_ROLE:ALL
